module slate::sema;

import slate::core;

import std::collections;

struct SemaContext
{
	CompilerContext* context;
	Allocator alloc;
	Scope* scope;
	String current_module;
	HashMap{String, ImportInfo} imports;
}

fn SemaContext* create(CompilerContext* context)
{
	SemaContext* ctx = alloc::new(context.alloc, SemaContext);

	ctx.context = context;
	ctx.alloc = context.alloc;
	ctx.scope = scope::create(ctx.alloc, {});
	ctx.imports.init(context.alloc);

	return ctx;
}

fn void index(SemaContext* ctx)
{
	foreach (SourceFile* sf : ctx.context.files.value_iter())
	{
		registry::register(ctx.context, sf);
	}
}

fn void analyze(SemaContext* ctx)
{
	foreach (SourceFile* sf : ctx.context.files.value_iter())
	{
		analyze_source_file(ctx, sf);
	}
}

<*
 @require ctx.context != null
*>
fn void analyze_source_file(SemaContext* ctx, SourceFile* sf)
{
	ctx.context.current_source_file = sf;

	ctx.scope = scope::create(ctx.alloc, {});

	//ctx.context.registry.functions.@each(; name, FunctionInfo* info)
	//{
	//	resolve::resolve_fn_signature(ctx, info);
	//};

	analyze_imports(ctx);

	run_variable_pass(ctx);
}

fn void analyze_imports(SemaContext* ctx)
{
	foreach (Node* node : ctx.context.current_source_file.ast.statements)
	{
		if (node.kind != IMPORT_DECL) continue;

		ImportDecl* imp = node.as(ImportDecl);

		foreach (Node* path : imp.paths)
		{
			PathAtom* expr = path.as(PathAtom);
			String full_path = expr.path.text;

			if (!ctx.context.modules.has_key(expr.path.text))
			{
				diagnostics::error(ctx.context, expr.range, "No module '%s' found", expr.path.text);
				continue;
			}

			if (ctx.imports.has_key(expr.path.text))
			{
				ImportInfo existing = ctx.imports.get(expr.path.text)!!;
				diagnostics::note(ctx.context, existing.node.range, "Previous import of '%s' was here", expr.path.text);
				diagnostics::error(ctx.context, expr.range, "Module '%s' is already imported", expr.path.text);
				continue;
			}

			diagnostics::log_debug("[AnalyzeImports]: Added import '%s'", expr.path.text);
			ctx.imports.set(expr.path.text, {expr.path.text, node});

			//if (!cursor::has_attribute(imp, NORECURSE, null))
			//{
			//	sz offset = 0;
			//	while (try idx = full_path[offset..].index_of("::"))
			//	{
			//		sz break_pos = offset + idx;
			//		String parent_prefix = full_path[:break_pos];

			//		if (!ctx.imports.has_key(parent_prefix) && ctx.context.modules.has_key(parent_prefix))
			//		{
			//			diagnostics::log_debug("[AnalyzeImports]: Added recursive import '%s'", parent_prefix);
			//			ctx.imports.set(parent_prefix, { parent_prefix, node });
			//		}

			//		offset = break_pos + 2;
			//	}
			//}

			if (try idx = full_path.rindex_of("::"))
			{
				String leaf = full_path[idx + 2..];
				if (!ctx.imports.has_key(leaf) && ctx.context.modules.has_key(leaf))
				{
					diagnostics::log_debug("[AnalyzeImports]: Added leaf import '%s'", leaf);
					ctx.imports.set(leaf, { full_path, node });
				}
			}
		}
	}
}
